export CLICOLOR=1
export PS1="\[\e[32m\]\u\[\e[m\]\[\e[32m\]@\[\e[m\]\[\e[32m\]\h\[\e[m\]:\[\e[34m\]\w\[\e[m\]\\$ "

# allow bash completion
if [ -f $(brew --prefix)/etc/bash_completion ]; then
    . $(brew --prefix)/etc/bash_completion
fi

# Homebrew settings
export PATH="/usr/local/sbin:/usr/local/bin/:$PATH"
export HOMEBREW_NO_AUTO_UPDATE=1
export HOMEBREW_CC=clang
export HOMEBREW_CXX=clang++

# Locale settings
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# aliases
alias UPDATE_REPO="cd ~/qgis/QGIS-Mac-Packager; git fetch origin; git rebase origin/master"
alias UPDATE_CRONJOB="cd ~/qgis/QGIS-Mac-Packager; cp scripts/run_cronjob.bash ../"
alias UPDATE_LAUNCHD="cd ~/qgis/QGIS-Mac-Packager; launchctl unload ~/Library/LaunchAgents/org.qgis.build.plist; cp scripts/org.qgis.build.plist ~/Library/LaunchAgents/; launchctl load ~/Library/LaunchAgents/org.qgis.build.plist"
alias CLEAN_BUILDS="cd ~/qgis; rm -rf ./builds/*/build;rm -rf ./builds/*/bundle;rm -rf ./builds/*/install"
alias REINSTALL_BREW="~/qgis/QGIS-Mac-Packager/scripts/install_brew.bash"
